In [1]:
import numpy as np

In [8]:
np.abs(-6)

6

In [9]:
x = np.linspace(start=-10, stop=10, num=101)

In [10]:
np.abs(x)

array([10. ,  9.8,  9.6,  9.4,  9.2,  9. ,  8.8,  8.6,  8.4,  8.2,  8. ,
        7.8,  7.6,  7.4,  7.2,  7. ,  6.8,  6.6,  6.4,  6.2,  6. ,  5.8,
        5.6,  5.4,  5.2,  5. ,  4.8,  4.6,  4.4,  4.2,  4. ,  3.8,  3.6,
        3.4,  3.2,  3. ,  2.8,  2.6,  2.4,  2.2,  2. ,  1.8,  1.6,  1.4,
        1.2,  1. ,  0.8,  0.6,  0.4,  0.2,  0. ,  0.2,  0.4,  0.6,  0.8,
        1. ,  1.2,  1.4,  1.6,  1.8,  2. ,  2.2,  2.4,  2.6,  2.8,  3. ,
        3.2,  3.4,  3.6,  3.8,  4. ,  4.2,  4.4,  4.6,  4.8,  5. ,  5.2,
        5.4,  5.6,  5.8,  6. ,  6.2,  6.4,  6.6,  6.8,  7. ,  7.2,  7.4,
        7.6,  7.8,  8. ,  8.2,  8.4,  8.6,  8.8,  9. ,  9.2,  9.4,  9.6,
        9.8, 10. ])

In [11]:
np.absolute([-1.0, -2.3, -5.0])

array([1. , 2.3, 5. ])

In [12]:
np.arange(9.0).reshape((3, 3))

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [17]:
c=np.arange(3)
c

array([0, 1, 2])

In [18]:
c+np.arange(9.0).reshape((3, 3))

array([[ 0.,  2.,  4.],
       [ 3.,  5.,  7.],
       [ 6.,  8., 10.]])

In [19]:
q=[[0,2,4],[3,5,7],[6,8,10]]

In [21]:
qq=[1,1,1]

In [22]:
q+qq

[[0, 2, 4], [3, 5, 7], [6, 8, 10], 1, 1, 1]

In [23]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.add()